### ISSUE TITLE
Better Android UI

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/Datus#3]
I jumped into Android development, although I am basically a Java developer. As you can see UI is not the best eye pleasing.

If you can offer better, you are more welcome to contribute ! 

Feel free to make it on your taste !

note: part of it, could be the CardView I suggest [here](https://github.com/bacloud14/Datus/issues/1), but this enhancement issue can go in any direction.

**Comment by AlinaStepanova** [comment]
Hi @bacloud14 I can try to help you with improving the UI

**Comment by bacloud14** [comment]
That is great Alina. It's yours 🤠 
Thanks and sweet coding.

**Comment by bacloud14** [comment]
Hello Alina, any follow up with this? Probably I will work on this tomorrow I hope,

**Comment by AlinaStepanova** [comment]
Hi @bacloud14 I've had several busy days lately, so I basically have just started working on this issue today. If it is fine for you I guess we can work in parallel on this task, or if you have time, you can wait a little bit more on my solution. It is up to you =)

**Comment by bacloud14** [comment]
Sure that is fantastic, no rush I just wanted to see how to collaborate, I wait for you first then.
